- id: app_gateway_backend_checks
  name: app_gateway_backend_checks
  description: Checks-backends
  entry: pre-commit-hooks/app_gateway_backend_checks.sh
  language: script
  
- id: exit1
  name: exit1
  description: Checks-backends
  entry: pre-commit-hooks/exit1.sh
  language: script
